server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: pswadr
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true
  port: 8443
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: your-client-id
            client-secret: your-client-secret
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
