server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: pswadr
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true
  port: 8443
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liHv1G4UqgCd0ruX
            client-secret: 3951d6db3a88586db6d6c548f98e01061199277b
            scope: profile, email
